extend = [
    { path = "../cargo-make/main.toml" },
    { path = "../cargo-make/trunk_server.toml" },
    { path = "../cargo-make/playwright-e2e.toml" },
]

[tasks.build]
command = "cargo"
args = ["+stable", "build-all-features"]
install_crate = "cargo-all-features"
