extend = [{ path = "../cargo-make/common.toml" }]

[tasks.verify-flow]
description = "Provides pre and post hooks for verify"
dependencies = ["pre-verify", "verify", "post-verify"]

[tasks.verify]
description = "Run all quality checks and tests"
dependencies = ["check-style", "test-unit-and-web"]

[tasks.test-unit-and-web]
description = "Run all unit and web tests"
dependencies = ["test-flow", "web-test-flow"]

[tasks.pre-verify]

[tasks.post-verify]
dependencies = ["clean-all"]

[tasks.web-test-flow]
description = "Provides pre and post hooks for web-test"
dependencies = ["pre-web-test", "web-test", "post-web-test"]

[tasks.pre-web-test]

[tasks.web-test]

[tasks.post-web-test]
