extend = [{ path = "../cargo-make/playwright.toml" }]

[tasks.test-e2e]
dependencies = ["setup-node", "test-playwright"]

[tasks.clean-all]
dependencies = ["clean-cargo", "clean-node_modules", "clean-playwright"]
