name: Check Examples

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-matrix-job:
    name: Get Examples
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

     - name: Set Matrix
        id: set-matrix
        run: |
          examples=$(ls examples | awk '{print "examples/" $0}' | grep -v examples/README.md | grep -v examples/gtk | grep -v examples/Makefile.toml | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix={\"directory\":$examples}" >> "$GITHUB_OUTPUT"

  matrix-job:
    name: Check
    needs: [setup-matrix-job]
    strategy:
      matrix: ${{ fromJSON(needs.setup-matrix-job.outputs.matrix) }}
      fail-fast: false
    uses: ./.github/workflows/run-example-task.yml
    with:
      directory: ${{ matrix.directory }}
      cargo_make_task: "check"
