name: Check Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get-leptos-changed:
    uses: ./.github/workflows/get-leptos-changed.yml

  get-examples-matrix:
    name: Get Examples Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install JQ Tool
        uses: mbround18/install-jq@v1

      - name: Set Matrix
        id: set-matrix
        run: |
          examples=$(ls examples | 
          awk '{print "examples/" $0}' | 
          grep -v examples/README.md | 
          grep -v examples/Makefile.toml | 
          grep -v examples/cargo-make | 
          grep -v examples/gtk | 
          jq -R -s -c 'split("\n")[:-1]')
          echo "Example Directories: $examples"
          echo "matrix={\"directory\":$examples}" >> "$GITHUB_OUTPUT"

  test:
    name: Check
    needs: [get-leptos-changed, get-examples-matrix]
    if: needs.get-leptos-changed.outputs.leptos_changed == 'true'
    strategy:
      matrix: ${{ fromJSON(needs.get-examples-matrix.outputs.matrix) }}
      fail-fast: false
    uses: ./.github/workflows/run-cargo-make-task.yml
    with:
      directory: ${{ matrix.directory }}
      cargo_make_task: "check"
