name: CI semver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get-leptos-changed:
    uses: ./.github/workflows/get-leptos-changed.yml

  test:
    name: Check semver
    needs: [get-leptos-changed]
    if: needs.get-leptos-changed.outputs.leptos_changed == 'true'
    uses: obi1kenobi/cargo-semver-checks-action@v2
    with:
      rust-toolchain: nightly-2024-01-29
