name: Verify Changed Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changed-dirs:
    name: Get Changes
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v36
        with:
          files: |
            examples
            !examples/cargo-make
            !examples/gtk
          json: true
          quotepath: false

      - name: List changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

      - name: Get changed examples
        id: changed-files
        uses: tj-actions/changed-files@v36
        with:
          dir_names: true
          dir_names_max_depth: "2"
          files: |
            examples
            !examples/cargo-make
            !examples/gtk
          json: true
          quotepath: false

      - name: List changed directories
        run: echo '${{ steps.changed-dirs.outputs.all_changed_files }}'

      - name: Set Matrix
        id: set-matrix
        run: |
          if [ ${{ steps.changed-dirs.outputs.any_changed }} == 'true' ]; then
            echo "matrix={\"directory\":${{ steps.changed-dirs.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"
          else
            echo "matrix={\"directory\":[\"INTERNAL\"]}" >> "$GITHUB_OUTPUT"
          fi

  matrix-job:
    name: Verify
    needs: [changed-dirs]
    strategy:
      matrix: ${{ fromJSON(needs.changed-dirs.outputs.matrix) }}
      fail-fast: false
    uses: ./.github/workflows/verify-example.yml
    with:
      project_dir: ${{ matrix.directory }}
