name: Verify Changed Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get-example-changed:
    uses: ./.github/workflows/example-changed.yml

  get-matrix:
    name: Get Changed Example Matrix
    needs: [get-example-changed]
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get example project directories that changed
        id: changed-dirs
        uses: tj-actions/changed-files@v36
        with:
          dir_names: true
          dir_names_max_depth: "2"
          files: |
            examples
            !examples/cargo-make
            !examples/gtk
            !examples/Makefile.toml
            !examples/README.md
          json: true
          quotepath: false

      - name: List example project directories that changed
        run: echo '${{ steps.changed-dirs.outputs.all_changed_files }}'

      - name: Set Matrix
        id: set-matrix
        run: |
          if [ ${{ needs.get-example-changed.outputs.example_changed }} == 'true' ]; then
            # Create matrix with changed directories
            echo "matrix={\"directory\":${{ steps.changed-dirs.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"
          else
            # Create matrix with one item to prevent an empty vector error
            echo "matrix={\"directory\":[\"NO_CHANGE\"]}" >> "$GITHUB_OUTPUT"
          fi

  test:
    name: Verify
    needs: [get-example-changed, get-matrix]
    if: needs.get-example-changed.outputs.example_changed == 'true'
    strategy:
      matrix: ${{ fromJSON(needs.get-matrix.outputs.matrix) }}
      fail-fast: false
    uses: ./.github/workflows/run-cargo-make-task.yml
    with:
      directory: ${{ matrix.directory }}
      cargo_make_task: "verify-flow"
