name: CI Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changed-dirs:
    name: Get Changed Examples
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed examples
        id: changed-dirs
        uses: tj-actions/changed-files@v36
        with:
          dir_names: true
          files: |
            examples
            !examples/cargo-make
            !examples/gtk
          json: true
          quotepath: false
      - name: List changed directories
        run: echo '${{ steps.changed-dirs.outputs.all_changed_files }}'
      - id: set-matrix
        run: echo "matrix={\"directory\":${{ steps.changed-dirs.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

  matrix-job:
    name: Verify
    needs: [changed-dirs]
    strategy:
      matrix: ${{ fromJSON(needs.changed-dirs.outputs.matrix) }}
      fail-fast: false
    uses: ./.github/workflows/verify-example.yml
    with:
      project_dir: ${{ matrix.directory }}
